# Theme 설정
remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin  : "default"

# 사이트 설정
title                  : "SQLD Study"
name                   : "Dekman Factory"
description            : "SQLD 자격증을 위한 정리 노트와 문제풀이"
url                    : "https://dekmanfactory.github.io"
baseurl                : "" # 루트에서 운영하므로 비워둠
repository             : "dekmanfactory/dekmanfactory.github.io"

# 기본 설정
locale: "ko-KR"
timezone: Asia/Seoul

author:
  name      : "Dekman"
  bio       : "SQLD 자격증 준비 중인 분들을 위한 실전 자료 제공"
  location  : "Korea"

# 첫 페이지는 index.md가 보여질 수 있도록 설정 필요 없음
# 기본 루트에 index.md가 있으면 자동으로 로딩됨
