# ---------------------------
# ✅ Theme 설정
# ---------------------------
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# ---------------------------
# ✅ 사이트 기본 정보
# ---------------------------
title: "SQLD Study"
name: "Dekman Factory"
description: "SQLD 자격증을 위한 정리 노트와 문제풀이"
url: "https://dekmanfactory.github.io"
baseurl: ""  # 루트 도메인에서 운영
repository: "dekmanfactory/dekmanfactory.github.io"

# ---------------------------
# ✅ 지역/언어 설정
# ---------------------------
locale: "ko-KR"
timezone: Asia/Seoul

# ---------------------------
# ✅ Author 정보
# ---------------------------
author:
  name: "Dekman"
  bio: "SQLD 자격증 준비 중인 분들을 위한 실전 자료 제공"
  location: "Korea"
  avatar: "/assets/images/avatar.png"  # 원하는 경우 아바타 이미지 경로 추가

# ---------------------------
# ✅ Plugins (필수!)
# ---------------------------
plugins:
  - jekyll-include-cache

# ---------------------------
# ✅ Navigation (상단 메뉴)
# ---------------------------
# 필요 시 메뉴 구성
#nav:
#  - title: "홈"
#    url: /
#  - title: "이론 정리"
#    url: /theory/
#  - title: "실전 문제"
#    url: /practice/
#  - title: "소개"
#    url: /about/

# ---------------------------
# ✅ Markdown, Permalink, 기타
# ---------------------------
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/

# ---------------------------
# ✅ SEO, Analytics (원하면 추가)
# ---------------------------
# seo:
#   type: "Blog"
# google_analytics: "G-XXXXXXX"
